# Generated by Django 5.0.7 on 2024-07-31 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(upload_to='chai_varieties/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Bk', 'Black'), ('Gr', 'Ginger'), ('Kl', 'Kiwi'), ('Ms', 'Masala'), ('Pl', 'Plain')], max_length=2)),
            ],
        ),
    ]
